//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.10.19 at 03:49:42 PM CEST 
//


package gmml;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/L:/bigcat_just_cvs/reactome_genmapp/src/GMML.xsd line 797)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Graphics">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="CenterX" use="required" type="{}Coordinate" />
 *                 &lt;attribute name="CenterY" use="required" type="{}Coordinate" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="OrganA"/>
 *             &lt;enumeration value="OrganB"/>
 *             &lt;enumeration value="OrganC"/>
 *             &lt;enumeration value="Ribosome"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface CellComponentShapeType {


    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getType();

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setType(java.lang.String value);

    /**
     * Gets the value of the graphics property.
     * 
     * @return
     *     possible object is
     *     {@link gmml.CellComponentShapeType.GraphicsType}
     */
    gmml.CellComponentShapeType.GraphicsType getGraphics();

    /**
     * Sets the value of the graphics property.
     * 
     * @param value
     *     allowed object is
     *     {@link gmml.CellComponentShapeType.GraphicsType}
     */
    void setGraphics(gmml.CellComponentShapeType.GraphicsType value);

    /**
     * Text from Notes is not
     * displayed on GenMAPP map or backpage
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNotes();

    /**
     * Text from Notes is not
     * displayed on GenMAPP map or backpage
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNotes(java.lang.String value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/L:/bigcat_just_cvs/reactome_genmapp/src/GMML.xsd line 809)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="CenterX" use="required" type="{}Coordinate" />
     *       &lt;attribute name="CenterY" use="required" type="{}Coordinate" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface GraphicsType {


        /**
         * Gets the value of the centerY property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigInteger}
         */
        java.math.BigInteger getCenterY();

        /**
         * Sets the value of the centerY property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigInteger}
         */
        void setCenterY(java.math.BigInteger value);

        /**
         * Gets the value of the centerX property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigInteger}
         */
        java.math.BigInteger getCenterX();

        /**
         * Sets the value of the centerX property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigInteger}
         */
        void setCenterX(java.math.BigInteger value);

    }

}
