//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.10.19 at 03:49:42 PM CEST 
//


package gmml;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/L:/bigcat_just_cvs/reactome_genmapp/src/GMML.xsd line 389)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}BaseElement">
 *       &lt;sequence>
 *         &lt;element name="Notes" type="{}NoteType" minOccurs="0"/>
 *         &lt;element name="Comment" type="{}CommentType" minOccurs="0"/>
 *         &lt;element name="Graphics">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Color" type="{}ColorType" default="Black" />
 *                 &lt;attribute name="EndX" type="{}Coordinate" />
 *                 &lt;attribute name="EndY" type="{}Coordinate" />
 *                 &lt;attribute name="StartX" type="{}Coordinate" />
 *                 &lt;attribute name="StartY" type="{}Coordinate" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Style" default="Solid">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Solid"/>
 *             &lt;enumeration value="Broken"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Line"/>
 *             &lt;enumeration value="Arrow"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface LineType
    extends gmml.BaseElement
{


    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getType();

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setType(java.lang.String value);

    /**
     * GenMAPP line comments
     * appear when line is right clicked They are currently
     * limited in length to 50 characters and are GenMAPP
     * REMARKS.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getComment();

    /**
     * GenMAPP line comments
     * appear when line is right clicked They are currently
     * limited in length to 50 characters and are GenMAPP
     * REMARKS.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setComment(java.lang.String value);

    /**
     * Gets the value of the graphics property.
     * 
     * @return
     *     possible object is
     *     {@link gmml.LineType.GraphicsType}
     */
    gmml.LineType.GraphicsType getGraphics();

    /**
     * Sets the value of the graphics property.
     * 
     * @param value
     *     allowed object is
     *     {@link gmml.LineType.GraphicsType}
     */
    void setGraphics(gmml.LineType.GraphicsType value);

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getStyle();

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setStyle(java.lang.String value);

    /**
     * Text from Notes is not
     * displayed on GenMAPP map or backpage.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNotes();

    /**
     * Text from Notes is not
     * displayed on GenMAPP map or backpage.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNotes(java.lang.String value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/L:/bigcat_just_cvs/reactome_genmapp/src/GMML.xsd line 414)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Color" type="{}ColorType" default="Black" />
     *       &lt;attribute name="EndX" type="{}Coordinate" />
     *       &lt;attribute name="EndY" type="{}Coordinate" />
     *       &lt;attribute name="StartX" type="{}Coordinate" />
     *       &lt;attribute name="StartY" type="{}Coordinate" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface GraphicsType {


        /**
         * Gets the value of the endX property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigInteger}
         */
        java.math.BigInteger getEndX();

        /**
         * Sets the value of the endX property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigInteger}
         */
        void setEndX(java.math.BigInteger value);

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         *     {@link java.math.BigInteger}
         *     byte[]
         */
        java.lang.Object getColor();

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         *     {@link java.math.BigInteger}
         *     byte[]
         */
        void setColor(java.lang.Object value);

        /**
         * Gets the value of the startY property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigInteger}
         */
        java.math.BigInteger getStartY();

        /**
         * Sets the value of the startY property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigInteger}
         */
        void setStartY(java.math.BigInteger value);

        /**
         * Gets the value of the startX property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigInteger}
         */
        java.math.BigInteger getStartX();

        /**
         * Sets the value of the startX property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigInteger}
         */
        void setStartX(java.math.BigInteger value);

        /**
         * Gets the value of the endY property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigInteger}
         */
        java.math.BigInteger getEndY();

        /**
         * Sets the value of the endY property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigInteger}
         */
        void setEndY(java.math.BigInteger value);

    }

}
