//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.10.19 at 03:49:42 PM CEST 
//


package gmml;


/**
 * This is text on a GenMAPP map that
 * can have associated comments.
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/L:/bigcat_just_cvs/reactome_genmapp/src/GMML.xsd line 573)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}BaseElement">
 *       &lt;sequence>
 *         &lt;element name="Notes" type="{}NoteType" minOccurs="0"/>
 *         &lt;element name="Comment" type="{}CommentType" minOccurs="0"/>
 *         &lt;element name="Graphics">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="CenterX" use="required" type="{}Coordinate" />
 *                 &lt;attribute name="CenterY" use="required" type="{}Coordinate" />
 *                 &lt;attribute name="Color" type="{}ColorType" />
 *                 &lt;attribute name="FontName" type="{}FontNameType" default="Arial" />
 *                 &lt;attribute name="FontSize" type="{}FontSizeType" default="12" />
 *                 &lt;attribute name="FontStyle" default="Normal">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="Normal"/>
 *                       &lt;enumeration value="Italic"/>
 *                       &lt;enumeration value="Underscore"/>
 *                       &lt;enumeration value="Strikethru"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="FontWeight" default="Regular">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="Regular"/>
 *                       &lt;enumeration value="Bold"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="Height" use="required" type="{}Dimension" />
 *                 &lt;attribute name="Width" use="required" type="{}Dimension" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="TextLabel" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface LabelType
    extends gmml.BaseElement
{


    /**
     * GenMAPP label comments
     * appear when label is right clicked They are currently
     * limited in length to 50 characters and are GenMAPP
     * REMARKS.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getComment();

    /**
     * GenMAPP label comments
     * appear when label is right clicked They are currently
     * limited in length to 50 characters and are GenMAPP
     * REMARKS.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setComment(java.lang.String value);

    /**
     * Gets the value of the graphics property.
     * 
     * @return
     *     possible object is
     *     {@link gmml.LabelType.GraphicsType}
     */
    gmml.LabelType.GraphicsType getGraphics();

    /**
     * Sets the value of the graphics property.
     * 
     * @param value
     *     allowed object is
     *     {@link gmml.LabelType.GraphicsType}
     */
    void setGraphics(gmml.LabelType.GraphicsType value);

    /**
     * Text from Notes is not
     * displayed on GenMAPP map or backpage.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getNotes();

    /**
     * Text from Notes is not
     * displayed on GenMAPP map or backpage.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setNotes(java.lang.String value);

    /**
     * Gets the value of the textLabel property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getTextLabel();

    /**
     * Sets the value of the textLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setTextLabel(java.lang.String value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/L:/bigcat_just_cvs/reactome_genmapp/src/GMML.xsd line 602)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="CenterX" use="required" type="{}Coordinate" />
     *       &lt;attribute name="CenterY" use="required" type="{}Coordinate" />
     *       &lt;attribute name="Color" type="{}ColorType" />
     *       &lt;attribute name="FontName" type="{}FontNameType" default="Arial" />
     *       &lt;attribute name="FontSize" type="{}FontSizeType" default="12" />
     *       &lt;attribute name="FontStyle" default="Normal">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="Normal"/>
     *             &lt;enumeration value="Italic"/>
     *             &lt;enumeration value="Underscore"/>
     *             &lt;enumeration value="Strikethru"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="FontWeight" default="Regular">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="Regular"/>
     *             &lt;enumeration value="Bold"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="Height" use="required" type="{}Dimension" />
     *       &lt;attribute name="Width" use="required" type="{}Dimension" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface GraphicsType {


        /**
         * Gets the value of the fontStyle property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getFontStyle();

        /**
         * Sets the value of the fontStyle property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setFontStyle(java.lang.String value);

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigInteger}
         *     byte[]{@link java.lang.String}
         */
        java.lang.Object getColor();

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigInteger}
         *     byte[]{@link java.lang.String}
         */
        void setColor(java.lang.Object value);

        /**
         * Gets the value of the fontWeight property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getFontWeight();

        /**
         * Sets the value of the fontWeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setFontWeight(java.lang.String value);

        /**
         * Gets the value of the width property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigInteger}
         */
        java.math.BigInteger getWidth();

        /**
         * Sets the value of the width property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigInteger}
         */
        void setWidth(java.math.BigInteger value);

        /**
         * Gets the value of the height property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigInteger}
         */
        java.math.BigInteger getHeight();

        /**
         * Sets the value of the height property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigInteger}
         */
        void setHeight(java.math.BigInteger value);

        /**
         * Gets the value of the fontName property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getFontName();

        /**
         * Sets the value of the fontName property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setFontName(java.lang.String value);

        /**
         * Gets the value of the centerY property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigInteger}
         */
        java.math.BigInteger getCenterY();

        /**
         * Sets the value of the centerY property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigInteger}
         */
        void setCenterY(java.math.BigInteger value);

        /**
         * Gets the value of the centerX property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigInteger}
         */
        java.math.BigInteger getCenterX();

        /**
         * Sets the value of the centerX property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigInteger}
         */
        void setCenterX(java.math.BigInteger value);

        /**
         * Gets the value of the fontSize property.
         * 
         * @return
         *     possible object is
         *     {@link java.math.BigInteger}
         */
        java.math.BigInteger getFontSize();

        /**
         * Sets the value of the fontSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.math.BigInteger}
         */
        void setFontSize(java.math.BigInteger value);

    }

}
